// Najiha Closet — Product catalog (demo data, replace with Firestore data later)
export const PRODUCTS = [
  {
    "id": "NC0001",
    "name": "Blush Tulle Party Frock",
    "category": "girls",
    "occasion": "New Arrivals",
    "price": 3890,
    "comparePrice": 4590,
    "stock": 10,
    "badge": "sale",
    "ageGroup": "5-6Y",
    "sizes": [
      "6-12M",
      "3-4Y",
      "0-3M"
    ],
    "color": "Ivory",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-1/500/650",
    "description": "Blush Tulle Party Frock crafted from soft, breathable fabric \u2014 a new arrivals favorite designed for comfort and everyday little adventures.",
    "rating": 4.2,
    "reviewCount": 14
  },
  {
    "id": "NC0002",
    "name": "Floral Cotton Sundress",
    "category": "girls",
    "occasion": "Casual",
    "price": 1990,
    "comparePrice": 2490,
    "stock": 0,
    "badge": "sale",
    "ageGroup": "6-9M",
    "sizes": [
      "4-5Y",
      "3-6M",
      "1-2Y",
      "2-3Y",
      "6-12M"
    ],
    "color": "Sky Blue",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-2/500/650",
    "description": "Floral Cotton Sundress crafted from soft, breathable fabric \u2014 a casual favorite designed for comfort and everyday little adventures.",
    "rating": 4.4,
    "reviewCount": 30
  },
  {
    "id": "NC0003",
    "name": "Rose Chiffon Gown",
    "category": "girls",
    "occasion": "New Arrivals",
    "price": 4690,
    "comparePrice": 4690,
    "stock": 15,
    "badge": "new",
    "ageGroup": "4-5Y",
    "sizes": [
      "3-4Y",
      "2-3Y",
      "6-12M",
      "0-3M"
    ],
    "color": "Charcoal Grey",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-3/500/650",
    "description": "Rose Chiffon Gown crafted from soft, breathable fabric \u2014 a new arrivals favorite designed for comfort and everyday little adventures.",
    "rating": 4.9,
    "reviewCount": 13
  },
  {
    "id": "NC0004",
    "name": "Lavender Layered Dress",
    "category": "girls",
    "occasion": "Casual",
    "price": 3190,
    "comparePrice": 3890,
    "stock": 12,
    "badge": "sale",
    "ageGroup": "9-12M",
    "sizes": [
      "3-6M",
      "0-3M",
      "3-4Y",
      "5-6Y",
      "6-12M"
    ],
    "color": "Sage Green",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-4/500/650",
    "description": "Lavender Layered Dress crafted from soft, breathable fabric \u2014 a casual favorite designed for comfort and everyday little adventures.",
    "rating": 4.4,
    "reviewCount": 84
  },
  {
    "id": "NC0005",
    "name": "Ivory Lace Frock",
    "category": "girls",
    "occasion": "New Arrivals",
    "price": 5190,
    "comparePrice": 0,
    "stock": 12,
    "badge": "",
    "ageGroup": "3-6M",
    "sizes": [
      "2-3Y",
      "3-4Y",
      "4-5Y"
    ],
    "color": "Burgundy",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-5/500/650",
    "description": "Ivory Lace Frock crafted from soft, breathable fabric \u2014 a new arrivals favorite designed for comfort and everyday little adventures.",
    "rating": 4.6,
    "reviewCount": 34
  },
  {
    "id": "NC0006",
    "name": "Peach Organza Dress",
    "category": "girls",
    "occasion": "Eid Collection",
    "price": 1890,
    "comparePrice": 0,
    "stock": 10,
    "badge": "sale",
    "ageGroup": "3-4Y",
    "sizes": [
      "3-4Y",
      "4-5Y",
      "0-3M",
      "3-6M",
      "5-6Y"
    ],
    "color": "Powder Blue",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-6/500/650",
    "description": "Peach Organza Dress crafted from soft, breathable fabric \u2014 a eid collection favorite designed for comfort and everyday little adventures.",
    "rating": 4.9,
    "reviewCount": 75
  },
  {
    "id": "NC0007",
    "name": "Mint Pinafore Dress",
    "category": "girls",
    "occasion": "New Arrivals",
    "price": 4290,
    "comparePrice": 4990,
    "stock": 20,
    "badge": "",
    "ageGroup": "5-6Y",
    "sizes": [
      "5-6Y",
      "3-6M",
      "6-12M",
      "4-5Y",
      "2-3Y"
    ],
    "color": "Charcoal Grey",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-7/500/650",
    "description": "Mint Pinafore Dress crafted from soft, breathable fabric \u2014 a new arrivals favorite designed for comfort and everyday little adventures.",
    "rating": 4.7,
    "reviewCount": 117
  },
  {
    "id": "NC0008",
    "name": "Golden Eid Frock",
    "category": "girls",
    "occasion": "New Arrivals",
    "price": 3490,
    "comparePrice": 0,
    "stock": 8,
    "badge": "sale",
    "ageGroup": "6-9M",
    "sizes": [
      "5-6Y",
      "0-3M",
      "4-5Y",
      "3-4Y",
      "3-6M"
    ],
    "color": "Coral",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-8/500/650",
    "description": "Golden Eid Frock crafted from soft, breathable fabric \u2014 a new arrivals favorite designed for comfort and everyday little adventures.",
    "rating": 4.7,
    "reviewCount": 52
  },
  {
    "id": "NC0009",
    "name": "Pink Ruffle Party Dress",
    "category": "girls",
    "occasion": "New Arrivals",
    "price": 2690,
    "comparePrice": 0,
    "stock": 20,
    "badge": "",
    "ageGroup": "2-3Y",
    "sizes": [
      "0-3M",
      "3-4Y",
      "4-5Y",
      "5-6Y",
      "6-12M"
    ],
    "color": "Ivory",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-9/500/650",
    "description": "Pink Ruffle Party Dress crafted from soft, breathable fabric \u2014 a new arrivals favorite designed for comfort and everyday little adventures.",
    "rating": 4.3,
    "reviewCount": 3
  },
  {
    "id": "NC0010",
    "name": "Butterfly Print Dress",
    "category": "girls",
    "occasion": "Party Wear",
    "price": 4290,
    "comparePrice": 0,
    "stock": 10,
    "badge": "sale",
    "ageGroup": "2-3Y",
    "sizes": [
      "3-6M",
      "4-5Y",
      "3-4Y",
      "6-12M",
      "5-6Y"
    ],
    "color": "Coral",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-10/500/650",
    "description": "Butterfly Print Dress crafted from soft, breathable fabric \u2014 a party wear favorite designed for comfort and everyday little adventures.",
    "rating": 5.0,
    "reviewCount": 70
  },
  {
    "id": "NC0011",
    "name": "Polka Dot Twirl Dress",
    "category": "girls",
    "occasion": "Party Wear",
    "price": 1490,
    "comparePrice": 0,
    "stock": 20,
    "badge": "new",
    "ageGroup": "0-3M",
    "sizes": [
      "3-4Y",
      "4-5Y",
      "6-12M"
    ],
    "color": "Mint Green",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-11/500/650",
    "description": "Polka Dot Twirl Dress crafted from soft, breathable fabric \u2014 a party wear favorite designed for comfort and everyday little adventures.",
    "rating": 5.0,
    "reviewCount": 13
  },
  {
    "id": "NC0012",
    "name": "Embroidered Velvet Frock",
    "category": "girls",
    "occasion": "Eid Collection",
    "price": 4290,
    "comparePrice": 0,
    "stock": 3,
    "badge": "sale",
    "ageGroup": "5-6Y",
    "sizes": [
      "5-6Y",
      "2-3Y",
      "3-6M"
    ],
    "color": "Sage Green",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-12/500/650",
    "description": "Embroidered Velvet Frock crafted from soft, breathable fabric \u2014 a eid collection favorite designed for comfort and everyday little adventures.",
    "rating": 5.0,
    "reviewCount": 72
  },
  {
    "id": "NC0013",
    "name": "Sequin Party Gown",
    "category": "girls",
    "occasion": "Casual",
    "price": 4690,
    "comparePrice": 0,
    "stock": 8,
    "badge": "",
    "ageGroup": "9-12M",
    "sizes": [
      "3-4Y",
      "1-2Y",
      "2-3Y",
      "4-5Y"
    ],
    "color": "Mint Green",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-13/500/650",
    "description": "Sequin Party Gown crafted from soft, breathable fabric \u2014 a casual favorite designed for comfort and everyday little adventures.",
    "rating": 4.2,
    "reviewCount": 73
  },
  {
    "id": "NC0014",
    "name": "Cotton Candy Frock",
    "category": "girls",
    "occasion": "Casual",
    "price": 1990,
    "comparePrice": 0,
    "stock": 0,
    "badge": "new",
    "ageGroup": "5-6Y",
    "sizes": [
      "0-3M",
      "3-6M",
      "5-6Y",
      "3-4Y",
      "6-12M"
    ],
    "color": "Mint Green",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-14/500/650",
    "description": "Cotton Candy Frock crafted from soft, breathable fabric \u2014 a casual favorite designed for comfort and everyday little adventures.",
    "rating": 4.6,
    "reviewCount": 72
  },
  {
    "id": "NC0015",
    "name": "Floral Puff Sleeve Dress",
    "category": "girls",
    "occasion": "New Arrivals",
    "price": 1890,
    "comparePrice": 0,
    "stock": 20,
    "badge": "sale",
    "ageGroup": "3-4Y",
    "sizes": [
      "4-5Y",
      "3-6M",
      "0-3M",
      "3-4Y"
    ],
    "color": "Rose Gold",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-15/500/650",
    "description": "Floral Puff Sleeve Dress crafted from soft, breathable fabric \u2014 a new arrivals favorite designed for comfort and everyday little adventures.",
    "rating": 4.6,
    "reviewCount": 96
  },
  {
    "id": "NC0016",
    "name": "Satin Bow Dress",
    "category": "girls",
    "occasion": "Party Wear",
    "price": 1490,
    "comparePrice": 0,
    "stock": 3,
    "badge": "new",
    "ageGroup": "9-12M",
    "sizes": [
      "3-4Y",
      "4-5Y",
      "0-3M",
      "3-6M"
    ],
    "color": "Charcoal Grey",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-16/500/650",
    "description": "Satin Bow Dress crafted from soft, breathable fabric \u2014 a party wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.5,
    "reviewCount": 38
  },
  {
    "id": "NC0017",
    "name": "Denim Pinafore Set",
    "category": "girls",
    "occasion": "Party Wear",
    "price": 2890,
    "comparePrice": 2890,
    "stock": 20,
    "badge": "new",
    "ageGroup": "3-4Y",
    "sizes": [
      "0-3M",
      "5-6Y",
      "3-6M"
    ],
    "color": "Mustard Yellow",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-17/500/650",
    "description": "Denim Pinafore Set crafted from soft, breathable fabric \u2014 a party wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.9,
    "reviewCount": 118
  },
  {
    "id": "NC0018",
    "name": "Princess Ball Gown",
    "category": "girls",
    "occasion": "New Arrivals",
    "price": 1490,
    "comparePrice": 1490,
    "stock": 15,
    "badge": "",
    "ageGroup": "4-5Y",
    "sizes": [
      "2-3Y",
      "1-2Y",
      "3-4Y",
      "5-6Y"
    ],
    "color": "Lavender",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-18/500/650",
    "description": "Princess Ball Gown crafted from soft, breathable fabric \u2014 a new arrivals favorite designed for comfort and everyday little adventures.",
    "rating": 4.4,
    "reviewCount": 10
  },
  {
    "id": "NC0019",
    "name": "Ruffled Maxi Dress",
    "category": "girls",
    "occasion": "Wedding Wear",
    "price": 3490,
    "comparePrice": 0,
    "stock": 0,
    "badge": "",
    "ageGroup": "5-6Y",
    "sizes": [
      "0-3M",
      "2-3Y",
      "1-2Y"
    ],
    "color": "Lavender",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-19/500/650",
    "description": "Ruffled Maxi Dress crafted from soft, breathable fabric \u2014 a wedding wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.6,
    "reviewCount": 111
  },
  {
    "id": "NC0020",
    "name": "Girls Kurti Set",
    "category": "girls",
    "occasion": "Casual",
    "price": 1890,
    "comparePrice": 1890,
    "stock": 8,
    "badge": "",
    "ageGroup": "3-6M",
    "sizes": [
      "1-2Y",
      "2-3Y",
      "4-5Y"
    ],
    "color": "Peach",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-20/500/650",
    "description": "Girls Kurti Set crafted from soft, breathable fabric \u2014 a casual favorite designed for comfort and everyday little adventures.",
    "rating": 4.7,
    "reviewCount": 43
  },
  {
    "id": "NC0021",
    "name": "Girls Lawn Suit",
    "category": "girls",
    "occasion": "Everyday",
    "price": 2190,
    "comparePrice": 2890,
    "stock": 12,
    "badge": "sale",
    "ageGroup": "2-3Y",
    "sizes": [
      "4-5Y",
      "3-6M",
      "3-4Y",
      "6-12M"
    ],
    "color": "Champagne",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-21/500/650",
    "description": "Girls Lawn Suit crafted from soft, breathable fabric \u2014 a everyday favorite designed for comfort and everyday little adventures.",
    "rating": 4.3,
    "reviewCount": 61
  },
  {
    "id": "NC0022",
    "name": "Girls Party Skirt Set",
    "category": "girls",
    "occasion": "Casual",
    "price": 3490,
    "comparePrice": 0,
    "stock": 3,
    "badge": "new",
    "ageGroup": "9-12M",
    "sizes": [
      "1-2Y",
      "2-3Y",
      "6-12M",
      "3-6M",
      "3-4Y"
    ],
    "color": "Rose Gold",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-22/500/650",
    "description": "Girls Party Skirt Set crafted from soft, breathable fabric \u2014 a casual favorite designed for comfort and everyday little adventures.",
    "rating": 4.6,
    "reviewCount": 72
  },
  {
    "id": "NC0023",
    "name": "Unicorn Print Dress",
    "category": "girls",
    "occasion": "Casual",
    "price": 4290,
    "comparePrice": 5190,
    "stock": 25,
    "badge": "new",
    "ageGroup": "3-6M",
    "sizes": [
      "2-3Y",
      "3-4Y",
      "0-3M",
      "3-6M",
      "6-12M"
    ],
    "color": "Sky Blue",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-23/500/650",
    "description": "Unicorn Print Dress crafted from soft, breathable fabric \u2014 a casual favorite designed for comfort and everyday little adventures.",
    "rating": 4.4,
    "reviewCount": 80
  },
  {
    "id": "NC0024",
    "name": "Rainbow Tutu Dress",
    "category": "girls",
    "occasion": "Eid Collection",
    "price": 1990,
    "comparePrice": 0,
    "stock": 8,
    "badge": "",
    "ageGroup": "0-3M",
    "sizes": [
      "5-6Y",
      "6-12M",
      "0-3M",
      "3-4Y",
      "1-2Y"
    ],
    "color": "Blush Pink",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-24/500/650",
    "description": "Rainbow Tutu Dress crafted from soft, breathable fabric \u2014 a eid collection favorite designed for comfort and everyday little adventures.",
    "rating": 4.3,
    "reviewCount": 36
  },
  {
    "id": "NC0025",
    "name": "Girls Winter Jumper Dress",
    "category": "girls",
    "occasion": "Eid Collection",
    "price": 1890,
    "comparePrice": 0,
    "stock": 25,
    "badge": "",
    "ageGroup": "5-6Y",
    "sizes": [
      "0-3M",
      "5-6Y",
      "4-5Y",
      "3-6M",
      "3-4Y"
    ],
    "color": "Lavender",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-25/500/650",
    "description": "Girls Winter Jumper Dress crafted from soft, breathable fabric \u2014 a eid collection favorite designed for comfort and everyday little adventures.",
    "rating": 4.2,
    "reviewCount": 49
  },
  {
    "id": "NC0026",
    "name": "Girls Corduroy Pinafore",
    "category": "girls",
    "occasion": "Eid Collection",
    "price": 4690,
    "comparePrice": 0,
    "stock": 0,
    "badge": "",
    "ageGroup": "5-6Y",
    "sizes": [
      "1-2Y",
      "3-4Y",
      "0-3M"
    ],
    "color": "Champagne",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-26/500/650",
    "description": "Girls Corduroy Pinafore crafted from soft, breathable fabric \u2014 a eid collection favorite designed for comfort and everyday little adventures.",
    "rating": 5.0,
    "reviewCount": 98
  },
  {
    "id": "NC0027",
    "name": "Girls Silk Party Dress",
    "category": "girls",
    "occasion": "New Arrivals",
    "price": 1890,
    "comparePrice": 0,
    "stock": 8,
    "badge": "sale",
    "ageGroup": "2-3Y",
    "sizes": [
      "4-5Y",
      "0-3M",
      "3-6M"
    ],
    "color": "Coral",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-27/500/650",
    "description": "Girls Silk Party Dress crafted from soft, breathable fabric \u2014 a new arrivals favorite designed for comfort and everyday little adventures.",
    "rating": 4.8,
    "reviewCount": 113
  },
  {
    "id": "NC0028",
    "name": "Girls Net Frock",
    "category": "girls",
    "occasion": "Party Wear",
    "price": 4290,
    "comparePrice": 0,
    "stock": 10,
    "badge": "sale",
    "ageGroup": "4-5Y",
    "sizes": [
      "3-6M",
      "1-2Y",
      "0-3M",
      "4-5Y",
      "5-6Y"
    ],
    "color": "Rose Gold",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-28/500/650",
    "description": "Girls Net Frock crafted from soft, breathable fabric \u2014 a party wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.8,
    "reviewCount": 32
  },
  {
    "id": "NC0029",
    "name": "Girls Cape Dress",
    "category": "girls",
    "occasion": "New Arrivals",
    "price": 1990,
    "comparePrice": 1990,
    "stock": 15,
    "badge": "",
    "ageGroup": "5-6Y",
    "sizes": [
      "3-6M",
      "4-5Y",
      "6-12M",
      "3-4Y"
    ],
    "color": "Peach",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-29/500/650",
    "description": "Girls Cape Dress crafted from soft, breathable fabric \u2014 a new arrivals favorite designed for comfort and everyday little adventures.",
    "rating": 4.9,
    "reviewCount": 45
  },
  {
    "id": "NC0030",
    "name": "Girls Two-Piece Set",
    "category": "girls",
    "occasion": "Eid Collection",
    "price": 1490,
    "comparePrice": 1490,
    "stock": 5,
    "badge": "",
    "ageGroup": "2-3Y",
    "sizes": [
      "3-6M",
      "2-3Y",
      "1-2Y"
    ],
    "color": "Peach",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-30/500/650",
    "description": "Girls Two-Piece Set crafted from soft, breathable fabric \u2014 a eid collection favorite designed for comfort and everyday little adventures.",
    "rating": 4.6,
    "reviewCount": 52
  },
  {
    "id": "NC0031",
    "name": "Blush Tulle Party Frock \u2013 Style 2",
    "category": "girls",
    "occasion": "Wedding Wear",
    "price": 3490,
    "comparePrice": 3490,
    "stock": 15,
    "badge": "new",
    "ageGroup": "2-3Y",
    "sizes": [
      "1-2Y",
      "6-12M",
      "5-6Y",
      "0-3M",
      "4-5Y"
    ],
    "color": "White",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-31/500/650",
    "description": "Blush Tulle Party Frock \u2013 Style 2 crafted from soft, breathable fabric \u2014 a wedding wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.8,
    "reviewCount": 41
  },
  {
    "id": "NC0032",
    "name": "Floral Cotton Sundress \u2013 Style 2",
    "category": "girls",
    "occasion": "New Arrivals",
    "price": 3190,
    "comparePrice": 3490,
    "stock": 12,
    "badge": "",
    "ageGroup": "3-4Y",
    "sizes": [
      "2-3Y",
      "5-6Y",
      "3-6M",
      "3-4Y",
      "1-2Y"
    ],
    "color": "White",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-32/500/650",
    "description": "Floral Cotton Sundress \u2013 Style 2 crafted from soft, breathable fabric \u2014 a new arrivals favorite designed for comfort and everyday little adventures.",
    "rating": 4.3,
    "reviewCount": 75
  },
  {
    "id": "NC0033",
    "name": "Rose Chiffon Gown \u2013 Style 2",
    "category": "girls",
    "occasion": "New Arrivals",
    "price": 2190,
    "comparePrice": 0,
    "stock": 0,
    "badge": "",
    "ageGroup": "2-3Y",
    "sizes": [
      "1-2Y",
      "5-6Y",
      "2-3Y",
      "3-4Y"
    ],
    "color": "Mustard Yellow",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-33/500/650",
    "description": "Rose Chiffon Gown \u2013 Style 2 crafted from soft, breathable fabric \u2014 a new arrivals favorite designed for comfort and everyday little adventures.",
    "rating": 4.7,
    "reviewCount": 68
  },
  {
    "id": "NC0034",
    "name": "Lavender Layered Dress \u2013 Style 2",
    "category": "girls",
    "occasion": "Party Wear",
    "price": 2890,
    "comparePrice": 0,
    "stock": 5,
    "badge": "new",
    "ageGroup": "9-12M",
    "sizes": [
      "3-4Y",
      "0-3M",
      "3-6M",
      "6-12M"
    ],
    "color": "Lavender",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-34/500/650",
    "description": "Lavender Layered Dress \u2013 Style 2 crafted from soft, breathable fabric \u2014 a party wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.4,
    "reviewCount": 63
  },
  {
    "id": "NC0035",
    "name": "Little Gentleman Suit",
    "category": "boys",
    "occasion": "Everyday",
    "price": 3490,
    "comparePrice": 0,
    "stock": 3,
    "badge": "",
    "ageGroup": "3-4Y",
    "sizes": [
      "1-2Y",
      "3-4Y",
      "4-5Y",
      "5-6Y"
    ],
    "color": "Mint Green",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-35/500/650",
    "description": "Little Gentleman Suit crafted from soft, breathable fabric \u2014 a everyday favorite designed for comfort and everyday little adventures.",
    "rating": 4.8,
    "reviewCount": 117
  },
  {
    "id": "NC0036",
    "name": "Boys Waistcoat Set",
    "category": "boys",
    "occasion": "Wedding Wear",
    "price": 4690,
    "comparePrice": 0,
    "stock": 3,
    "badge": "",
    "ageGroup": "4-5Y",
    "sizes": [
      "6-12M",
      "4-5Y",
      "3-4Y"
    ],
    "color": "Blush Pink",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-36/500/650",
    "description": "Boys Waistcoat Set crafted from soft, breathable fabric \u2014 a wedding wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.9,
    "reviewCount": 18
  },
  {
    "id": "NC0037",
    "name": "Boys Kurta Shalwar",
    "category": "boys",
    "occasion": "Party Wear",
    "price": 2890,
    "comparePrice": 3190,
    "stock": 25,
    "badge": "",
    "ageGroup": "4-5Y",
    "sizes": [
      "4-5Y",
      "5-6Y",
      "2-3Y",
      "1-2Y"
    ],
    "color": "Mustard Yellow",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-37/500/650",
    "description": "Boys Kurta Shalwar crafted from soft, breathable fabric \u2014 a party wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.4,
    "reviewCount": 84
  },
  {
    "id": "NC0038",
    "name": "Boys Denim Dungaree",
    "category": "boys",
    "occasion": "Party Wear",
    "price": 2190,
    "comparePrice": 0,
    "stock": 25,
    "badge": "",
    "ageGroup": "1-2Y",
    "sizes": [
      "1-2Y",
      "6-12M",
      "5-6Y",
      "0-3M",
      "4-5Y"
    ],
    "color": "Rose Gold",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-38/500/650",
    "description": "Boys Denim Dungaree crafted from soft, breathable fabric \u2014 a party wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.6,
    "reviewCount": 20
  },
  {
    "id": "NC0039",
    "name": "Boys Party Blazer Set",
    "category": "boys",
    "occasion": "Wedding Wear",
    "price": 1890,
    "comparePrice": 2590,
    "stock": 5,
    "badge": "sale",
    "ageGroup": "4-5Y",
    "sizes": [
      "4-5Y",
      "1-2Y",
      "6-12M"
    ],
    "color": "Peach",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-39/500/650",
    "description": "Boys Party Blazer Set crafted from soft, breathable fabric \u2014 a wedding wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.9,
    "reviewCount": 52
  },
  {
    "id": "NC0040",
    "name": "Boys Casual Polo Set",
    "category": "boys",
    "occasion": "Everyday",
    "price": 4690,
    "comparePrice": 0,
    "stock": 0,
    "badge": "",
    "ageGroup": "5-6Y",
    "sizes": [
      "0-3M",
      "6-12M",
      "4-5Y",
      "1-2Y"
    ],
    "color": "Sky Blue",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-40/500/650",
    "description": "Boys Casual Polo Set crafted from soft, breathable fabric \u2014 a everyday favorite designed for comfort and everyday little adventures.",
    "rating": 4.8,
    "reviewCount": 117
  },
  {
    "id": "NC0041",
    "name": "Boys Printed T-Shirt Set",
    "category": "boys",
    "occasion": "New Arrivals",
    "price": 1990,
    "comparePrice": 0,
    "stock": 10,
    "badge": "",
    "ageGroup": "6-9M",
    "sizes": [
      "0-3M",
      "1-2Y",
      "6-12M",
      "4-5Y"
    ],
    "color": "Sage Green",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-41/500/650",
    "description": "Boys Printed T-Shirt Set crafted from soft, breathable fabric \u2014 a new arrivals favorite designed for comfort and everyday little adventures.",
    "rating": 4.3,
    "reviewCount": 82
  },
  {
    "id": "NC0042",
    "name": "Boys Eid Kurta",
    "category": "boys",
    "occasion": "Eid Collection",
    "price": 3190,
    "comparePrice": 3490,
    "stock": 0,
    "badge": "new",
    "ageGroup": "3-4Y",
    "sizes": [
      "4-5Y",
      "3-6M",
      "1-2Y",
      "5-6Y",
      "0-3M"
    ],
    "color": "Rose Gold",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-42/500/650",
    "description": "Boys Eid Kurta crafted from soft, breathable fabric \u2014 a eid collection favorite designed for comfort and everyday little adventures.",
    "rating": 4.5,
    "reviewCount": 100
  },
  {
    "id": "NC0043",
    "name": "Boys Formal Shirt Set",
    "category": "boys",
    "occasion": "Wedding Wear",
    "price": 2690,
    "comparePrice": 3590,
    "stock": 15,
    "badge": "",
    "ageGroup": "0-3M",
    "sizes": [
      "5-6Y",
      "0-3M",
      "3-4Y"
    ],
    "color": "Rose Gold",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-43/500/650",
    "description": "Boys Formal Shirt Set crafted from soft, breathable fabric \u2014 a wedding wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.3,
    "reviewCount": 86
  },
  {
    "id": "NC0044",
    "name": "Boys Cargo Shorts Set",
    "category": "boys",
    "occasion": "Everyday",
    "price": 1490,
    "comparePrice": 0,
    "stock": 8,
    "badge": "sale",
    "ageGroup": "3-6M",
    "sizes": [
      "6-12M",
      "3-6M",
      "4-5Y"
    ],
    "color": "Burgundy",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-44/500/650",
    "description": "Boys Cargo Shorts Set crafted from soft, breathable fabric \u2014 a everyday favorite designed for comfort and everyday little adventures.",
    "rating": 4.6,
    "reviewCount": 35
  },
  {
    "id": "NC0045",
    "name": "Boys Hoodie Set",
    "category": "boys",
    "occasion": "Wedding Wear",
    "price": 4690,
    "comparePrice": 0,
    "stock": 3,
    "badge": "sale",
    "ageGroup": "3-4Y",
    "sizes": [
      "3-6M",
      "2-3Y",
      "0-3M",
      "6-12M"
    ],
    "color": "Peach",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-45/500/650",
    "description": "Boys Hoodie Set crafted from soft, breathable fabric \u2014 a wedding wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.4,
    "reviewCount": 78
  },
  {
    "id": "NC0046",
    "name": "Boys Striped Romper",
    "category": "boys",
    "occasion": "Wedding Wear",
    "price": 4290,
    "comparePrice": 0,
    "stock": 8,
    "badge": "new",
    "ageGroup": "0-3M",
    "sizes": [
      "2-3Y",
      "4-5Y",
      "3-4Y",
      "5-6Y",
      "0-3M"
    ],
    "color": "Rose Gold",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-46/500/650",
    "description": "Boys Striped Romper crafted from soft, breathable fabric \u2014 a wedding wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.7,
    "reviewCount": 11
  },
  {
    "id": "NC0047",
    "name": "Boys Bowtie Suit",
    "category": "boys",
    "occasion": "New Arrivals",
    "price": 3190,
    "comparePrice": 0,
    "stock": 0,
    "badge": "",
    "ageGroup": "6-9M",
    "sizes": [
      "3-6M",
      "1-2Y",
      "6-12M",
      "4-5Y"
    ],
    "color": "Peach",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-47/500/650",
    "description": "Boys Bowtie Suit crafted from soft, breathable fabric \u2014 a new arrivals favorite designed for comfort and everyday little adventures.",
    "rating": 4.6,
    "reviewCount": 86
  },
  {
    "id": "NC0048",
    "name": "Boys Checkered Shirt Set",
    "category": "boys",
    "occasion": "Eid Collection",
    "price": 2190,
    "comparePrice": 0,
    "stock": 25,
    "badge": "",
    "ageGroup": "2-3Y",
    "sizes": [
      "4-5Y",
      "5-6Y",
      "3-4Y",
      "2-3Y"
    ],
    "color": "Sage Green",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-48/500/650",
    "description": "Boys Checkered Shirt Set crafted from soft, breathable fabric \u2014 a eid collection favorite designed for comfort and everyday little adventures.",
    "rating": 4.9,
    "reviewCount": 38
  },
  {
    "id": "NC0049",
    "name": "Boys Sherwani",
    "category": "boys",
    "occasion": "Party Wear",
    "price": 2890,
    "comparePrice": 3190,
    "stock": 15,
    "badge": "",
    "ageGroup": "4-5Y",
    "sizes": [
      "5-6Y",
      "4-5Y",
      "6-12M"
    ],
    "color": "Mint Green",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-49/500/650",
    "description": "Boys Sherwani crafted from soft, breathable fabric \u2014 a party wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.4,
    "reviewCount": 38
  },
  {
    "id": "NC0050",
    "name": "Boys Summer Shorts Set",
    "category": "boys",
    "occasion": "Wedding Wear",
    "price": 3490,
    "comparePrice": 0,
    "stock": 10,
    "badge": "new",
    "ageGroup": "9-12M",
    "sizes": [
      "1-2Y",
      "0-3M",
      "3-6M",
      "5-6Y",
      "2-3Y"
    ],
    "color": "Sky Blue",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-50/500/650",
    "description": "Boys Summer Shorts Set crafted from soft, breathable fabric \u2014 a wedding wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.8,
    "reviewCount": 60
  },
  {
    "id": "NC0051",
    "name": "Boys Winter Sweater Set",
    "category": "boys",
    "occasion": "Everyday",
    "price": 4690,
    "comparePrice": 4690,
    "stock": 8,
    "badge": "",
    "ageGroup": "5-6Y",
    "sizes": [
      "1-2Y",
      "6-12M",
      "3-4Y",
      "2-3Y",
      "4-5Y"
    ],
    "color": "Charcoal Grey",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-51/500/650",
    "description": "Boys Winter Sweater Set crafted from soft, breathable fabric \u2014 a everyday favorite designed for comfort and everyday little adventures.",
    "rating": 5.0,
    "reviewCount": 73
  },
  {
    "id": "NC0052",
    "name": "Boys Denim Jacket Set",
    "category": "boys",
    "occasion": "Eid Collection",
    "price": 2490,
    "comparePrice": 0,
    "stock": 20,
    "badge": "",
    "ageGroup": "3-6M",
    "sizes": [
      "2-3Y",
      "3-6M",
      "0-3M",
      "4-5Y"
    ],
    "color": "Sky Blue",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-52/500/650",
    "description": "Boys Denim Jacket Set crafted from soft, breathable fabric \u2014 a eid collection favorite designed for comfort and everyday little adventures.",
    "rating": 4.8,
    "reviewCount": 26
  },
  {
    "id": "NC0053",
    "name": "Boys Cotton Playsuit",
    "category": "boys",
    "occasion": "Eid Collection",
    "price": 1990,
    "comparePrice": 2290,
    "stock": 10,
    "badge": "",
    "ageGroup": "6-9M",
    "sizes": [
      "1-2Y",
      "6-12M",
      "3-6M"
    ],
    "color": "Powder Blue",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-53/500/650",
    "description": "Boys Cotton Playsuit crafted from soft, breathable fabric \u2014 a eid collection favorite designed for comfort and everyday little adventures.",
    "rating": 4.6,
    "reviewCount": 38
  },
  {
    "id": "NC0054",
    "name": "Boys Traditional Set",
    "category": "boys",
    "occasion": "Wedding Wear",
    "price": 1490,
    "comparePrice": 0,
    "stock": 25,
    "badge": "",
    "ageGroup": "1-2Y",
    "sizes": [
      "6-12M",
      "3-4Y",
      "1-2Y",
      "0-3M",
      "2-3Y"
    ],
    "color": "Mustard Yellow",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-54/500/650",
    "description": "Boys Traditional Set crafted from soft, breathable fabric \u2014 a wedding wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.5,
    "reviewCount": 9
  },
  {
    "id": "NC0055",
    "name": "Boys Graphic Tee Set",
    "category": "boys",
    "occasion": "Wedding Wear",
    "price": 2190,
    "comparePrice": 0,
    "stock": 20,
    "badge": "new",
    "ageGroup": "0-3M",
    "sizes": [
      "4-5Y",
      "1-2Y",
      "0-3M"
    ],
    "color": "Lavender",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-55/500/650",
    "description": "Boys Graphic Tee Set crafted from soft, breathable fabric \u2014 a wedding wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.7,
    "reviewCount": 41
  },
  {
    "id": "NC0056",
    "name": "Boys Linen Shirt Set",
    "category": "boys",
    "occasion": "Everyday",
    "price": 1690,
    "comparePrice": 0,
    "stock": 3,
    "badge": "",
    "ageGroup": "1-2Y",
    "sizes": [
      "1-2Y",
      "4-5Y",
      "2-3Y",
      "5-6Y",
      "3-4Y"
    ],
    "color": "Sage Green",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-56/500/650",
    "description": "Boys Linen Shirt Set crafted from soft, breathable fabric \u2014 a everyday favorite designed for comfort and everyday little adventures.",
    "rating": 4.5,
    "reviewCount": 75
  },
  {
    "id": "NC0057",
    "name": "Boys Sports Tracksuit",
    "category": "boys",
    "occasion": "Party Wear",
    "price": 3490,
    "comparePrice": 4190,
    "stock": 3,
    "badge": "sale",
    "ageGroup": "6-9M",
    "sizes": [
      "1-2Y",
      "6-12M",
      "3-4Y",
      "0-3M",
      "3-6M"
    ],
    "color": "Charcoal Grey",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-57/500/650",
    "description": "Boys Sports Tracksuit crafted from soft, breathable fabric \u2014 a party wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.2,
    "reviewCount": 60
  },
  {
    "id": "NC0058",
    "name": "Boys Overall Set",
    "category": "boys",
    "occasion": "New Arrivals",
    "price": 4290,
    "comparePrice": 0,
    "stock": 10,
    "badge": "new",
    "ageGroup": "4-5Y",
    "sizes": [
      "2-3Y",
      "3-4Y",
      "6-12M"
    ],
    "color": "Ivory",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-58/500/650",
    "description": "Boys Overall Set crafted from soft, breathable fabric \u2014 a new arrivals favorite designed for comfort and everyday little adventures.",
    "rating": 4.9,
    "reviewCount": 103
  },
  {
    "id": "NC0059",
    "name": "Boys Vest & Shorts Set",
    "category": "boys",
    "occasion": "Eid Collection",
    "price": 4690,
    "comparePrice": 0,
    "stock": 8,
    "badge": "",
    "ageGroup": "6-9M",
    "sizes": [
      "1-2Y",
      "3-4Y",
      "3-6M"
    ],
    "color": "Ivory",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-59/500/650",
    "description": "Boys Vest & Shorts Set crafted from soft, breathable fabric \u2014 a eid collection favorite designed for comfort and everyday little adventures.",
    "rating": 4.8,
    "reviewCount": 79
  },
  {
    "id": "NC0060",
    "name": "Little Gentleman Suit \u2013 Style 2",
    "category": "boys",
    "occasion": "New Arrivals",
    "price": 4290,
    "comparePrice": 0,
    "stock": 10,
    "badge": "",
    "ageGroup": "3-4Y",
    "sizes": [
      "5-6Y",
      "3-4Y",
      "6-12M"
    ],
    "color": "Powder Blue",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-60/500/650",
    "description": "Little Gentleman Suit \u2013 Style 2 crafted from soft, breathable fabric \u2014 a new arrivals favorite designed for comfort and everyday little adventures.",
    "rating": 4.6,
    "reviewCount": 13
  },
  {
    "id": "NC0061",
    "name": "Boys Waistcoat Set \u2013 Style 2",
    "category": "boys",
    "occasion": "Wedding Wear",
    "price": 3490,
    "comparePrice": 3790,
    "stock": 12,
    "badge": "",
    "ageGroup": "0-3M",
    "sizes": [
      "3-6M",
      "5-6Y",
      "3-4Y"
    ],
    "color": "Coral",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-61/500/650",
    "description": "Boys Waistcoat Set \u2013 Style 2 crafted from soft, breathable fabric \u2014 a wedding wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.4,
    "reviewCount": 8
  },
  {
    "id": "NC0062",
    "name": "Boys Kurta Shalwar \u2013 Style 2",
    "category": "boys",
    "occasion": "Casual",
    "price": 4690,
    "comparePrice": 0,
    "stock": 20,
    "badge": "",
    "ageGroup": "4-5Y",
    "sizes": [
      "6-12M",
      "2-3Y",
      "1-2Y",
      "3-4Y"
    ],
    "color": "Rose Gold",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-62/500/650",
    "description": "Boys Kurta Shalwar \u2013 Style 2 crafted from soft, breathable fabric \u2014 a casual favorite designed for comfort and everyday little adventures.",
    "rating": 4.5,
    "reviewCount": 16
  },
  {
    "id": "NC0063",
    "name": "Boys Denim Dungaree \u2013 Style 2",
    "category": "boys",
    "occasion": "Casual",
    "price": 5190,
    "comparePrice": 5490,
    "stock": 20,
    "badge": "",
    "ageGroup": "2-3Y",
    "sizes": [
      "4-5Y",
      "5-6Y",
      "2-3Y",
      "0-3M",
      "1-2Y"
    ],
    "color": "Powder Blue",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-63/500/650",
    "description": "Boys Denim Dungaree \u2013 Style 2 crafted from soft, breathable fabric \u2014 a casual favorite designed for comfort and everyday little adventures.",
    "rating": 5.0,
    "reviewCount": 54
  },
  {
    "id": "NC0064",
    "name": "Boys Party Blazer Set \u2013 Style 2",
    "category": "boys",
    "occasion": "Wedding Wear",
    "price": 5190,
    "comparePrice": 0,
    "stock": 0,
    "badge": "",
    "ageGroup": "4-5Y",
    "sizes": [
      "0-3M",
      "3-6M",
      "2-3Y",
      "6-12M"
    ],
    "color": "White",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-64/500/650",
    "description": "Boys Party Blazer Set \u2013 Style 2 crafted from soft, breathable fabric \u2014 a wedding wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.2,
    "reviewCount": 37
  },
  {
    "id": "NC0065",
    "name": "Boys Casual Polo Set \u2013 Style 2",
    "category": "boys",
    "occasion": "Party Wear",
    "price": 3190,
    "comparePrice": 3190,
    "stock": 20,
    "badge": "",
    "ageGroup": "6-9M",
    "sizes": [
      "0-3M",
      "3-4Y",
      "2-3Y"
    ],
    "color": "Powder Blue",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-65/500/650",
    "description": "Boys Casual Polo Set \u2013 Style 2 crafted from soft, breathable fabric \u2014 a party wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.6,
    "reviewCount": 14
  },
  {
    "id": "NC0066",
    "name": "Boys Printed T-Shirt Set \u2013 Style 2",
    "category": "boys",
    "occasion": "Eid Collection",
    "price": 1990,
    "comparePrice": 0,
    "stock": 3,
    "badge": "",
    "ageGroup": "5-6Y",
    "sizes": [
      "6-12M",
      "1-2Y",
      "3-4Y"
    ],
    "color": "Sky Blue",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-66/500/650",
    "description": "Boys Printed T-Shirt Set \u2013 Style 2 crafted from soft, breathable fabric \u2014 a eid collection favorite designed for comfort and everyday little adventures.",
    "rating": 4.9,
    "reviewCount": 63
  },
  {
    "id": "NC0067",
    "name": "Boys Eid Kurta \u2013 Style 2",
    "category": "boys",
    "occasion": "Eid Collection",
    "price": 1990,
    "comparePrice": 0,
    "stock": 5,
    "badge": "",
    "ageGroup": "3-4Y",
    "sizes": [
      "6-12M",
      "4-5Y",
      "0-3M"
    ],
    "color": "Rose Gold",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-67/500/650",
    "description": "Boys Eid Kurta \u2013 Style 2 crafted from soft, breathable fabric \u2014 a eid collection favorite designed for comfort and everyday little adventures.",
    "rating": 4.6,
    "reviewCount": 108
  },
  {
    "id": "NC0068",
    "name": "Boys Formal Shirt Set \u2013 Style 2",
    "category": "boys",
    "occasion": "Wedding Wear",
    "price": 1490,
    "comparePrice": 1490,
    "stock": 20,
    "badge": "sale",
    "ageGroup": "3-4Y",
    "sizes": [
      "5-6Y",
      "6-12M",
      "4-5Y",
      "2-3Y"
    ],
    "color": "Mustard Yellow",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-68/500/650",
    "description": "Boys Formal Shirt Set \u2013 Style 2 crafted from soft, breathable fabric \u2014 a wedding wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.9,
    "reviewCount": 92
  },
  {
    "id": "NC0069",
    "name": "Baby Cotton Romper",
    "category": "baby",
    "occasion": "New Arrivals",
    "price": 1990,
    "comparePrice": 0,
    "stock": 8,
    "badge": "",
    "ageGroup": "3-4Y",
    "sizes": [
      "3-4Y",
      "5-6Y",
      "1-2Y"
    ],
    "color": "Peach",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-69/500/650",
    "description": "Baby Cotton Romper crafted from soft, breathable fabric \u2014 a new arrivals favorite designed for comfort and everyday little adventures.",
    "rating": 4.8,
    "reviewCount": 86
  },
  {
    "id": "NC0070",
    "name": "Baby Floral Onesie",
    "category": "baby",
    "occasion": "Wedding Wear",
    "price": 1890,
    "comparePrice": 0,
    "stock": 0,
    "badge": "sale",
    "ageGroup": "4-5Y",
    "sizes": [
      "3-4Y",
      "4-5Y",
      "0-3M",
      "1-2Y",
      "5-6Y"
    ],
    "color": "Blush Pink",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-70/500/650",
    "description": "Baby Floral Onesie crafted from soft, breathable fabric \u2014 a wedding wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.5,
    "reviewCount": 86
  },
  {
    "id": "NC0071",
    "name": "Baby Sleep Suit",
    "category": "baby",
    "occasion": "Eid Collection",
    "price": 1890,
    "comparePrice": 2790,
    "stock": 10,
    "badge": "",
    "ageGroup": "4-5Y",
    "sizes": [
      "4-5Y",
      "3-4Y",
      "0-3M",
      "6-12M",
      "1-2Y"
    ],
    "color": "Sage Green",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-71/500/650",
    "description": "Baby Sleep Suit crafted from soft, breathable fabric \u2014 a eid collection favorite designed for comfort and everyday little adventures.",
    "rating": 4.7,
    "reviewCount": 33
  },
  {
    "id": "NC0072",
    "name": "Baby Knit Cardigan Set",
    "category": "baby",
    "occasion": "Party Wear",
    "price": 3890,
    "comparePrice": 0,
    "stock": 10,
    "badge": "sale",
    "ageGroup": "1-2Y",
    "sizes": [
      "3-6M",
      "1-2Y",
      "0-3M",
      "3-4Y",
      "4-5Y"
    ],
    "color": "Champagne",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-72/500/650",
    "description": "Baby Knit Cardigan Set crafted from soft, breathable fabric \u2014 a party wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.5,
    "reviewCount": 10
  },
  {
    "id": "NC0073",
    "name": "Baby Header Bib Set",
    "category": "baby",
    "occasion": "Party Wear",
    "price": 2190,
    "comparePrice": 0,
    "stock": 15,
    "badge": "sale",
    "ageGroup": "6-9M",
    "sizes": [
      "4-5Y",
      "2-3Y",
      "3-4Y"
    ],
    "color": "Lavender",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-73/500/650",
    "description": "Baby Header Bib Set crafted from soft, breathable fabric \u2014 a party wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.9,
    "reviewCount": 82
  },
  {
    "id": "NC0074",
    "name": "Baby Soft Booties Set",
    "category": "baby",
    "occasion": "Everyday",
    "price": 3890,
    "comparePrice": 4390,
    "stock": 5,
    "badge": "sale",
    "ageGroup": "1-2Y",
    "sizes": [
      "2-3Y",
      "1-2Y",
      "6-12M",
      "0-3M"
    ],
    "color": "White",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-74/500/650",
    "description": "Baby Soft Booties Set crafted from soft, breathable fabric \u2014 a everyday favorite designed for comfort and everyday little adventures.",
    "rating": 4.3,
    "reviewCount": 47
  },
  {
    "id": "NC0075",
    "name": "Baby Cotton Jumpsuit",
    "category": "baby",
    "occasion": "Party Wear",
    "price": 3490,
    "comparePrice": 3790,
    "stock": 10,
    "badge": "",
    "ageGroup": "3-4Y",
    "sizes": [
      "1-2Y",
      "5-6Y",
      "4-5Y",
      "0-3M"
    ],
    "color": "Burgundy",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-75/500/650",
    "description": "Baby Cotton Jumpsuit crafted from soft, breathable fabric \u2014 a party wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.4,
    "reviewCount": 92
  },
  {
    "id": "NC0076",
    "name": "Baby Party Romper",
    "category": "baby",
    "occasion": "Everyday",
    "price": 2190,
    "comparePrice": 3090,
    "stock": 15,
    "badge": "",
    "ageGroup": "1-2Y",
    "sizes": [
      "0-3M",
      "2-3Y",
      "3-4Y"
    ],
    "color": "Coral",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-76/500/650",
    "description": "Baby Party Romper crafted from soft, breathable fabric \u2014 a everyday favorite designed for comfort and everyday little adventures.",
    "rating": 4.7,
    "reviewCount": 48
  },
  {
    "id": "NC0077",
    "name": "Baby Fleece Set",
    "category": "baby",
    "occasion": "Everyday",
    "price": 1990,
    "comparePrice": 0,
    "stock": 10,
    "badge": "sale",
    "ageGroup": "0-3M",
    "sizes": [
      "3-6M",
      "3-4Y",
      "4-5Y",
      "0-3M",
      "6-12M"
    ],
    "color": "Burgundy",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-77/500/650",
    "description": "Baby Fleece Set crafted from soft, breathable fabric \u2014 a everyday favorite designed for comfort and everyday little adventures.",
    "rating": 4.3,
    "reviewCount": 119
  },
  {
    "id": "NC0078",
    "name": "Baby Muslin Set",
    "category": "baby",
    "occasion": "Eid Collection",
    "price": 2190,
    "comparePrice": 2490,
    "stock": 5,
    "badge": "sale",
    "ageGroup": "6-9M",
    "sizes": [
      "3-4Y",
      "2-3Y",
      "4-5Y"
    ],
    "color": "Powder Blue",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-78/500/650",
    "description": "Baby Muslin Set crafted from soft, breathable fabric \u2014 a eid collection favorite designed for comfort and everyday little adventures.",
    "rating": 5.0,
    "reviewCount": 106
  },
  {
    "id": "NC0079",
    "name": "Baby Girl Headband Dress",
    "category": "baby",
    "occasion": "Wedding Wear",
    "price": 2190,
    "comparePrice": 0,
    "stock": 12,
    "badge": "new",
    "ageGroup": "2-3Y",
    "sizes": [
      "3-6M",
      "5-6Y",
      "4-5Y",
      "1-2Y"
    ],
    "color": "Ivory",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-79/500/650",
    "description": "Baby Girl Headband Dress crafted from soft, breathable fabric \u2014 a wedding wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.2,
    "reviewCount": 71
  },
  {
    "id": "NC0080",
    "name": "Baby Boy Dungaree Set",
    "category": "baby",
    "occasion": "Casual",
    "price": 1690,
    "comparePrice": 0,
    "stock": 10,
    "badge": "",
    "ageGroup": "5-6Y",
    "sizes": [
      "3-4Y",
      "0-3M",
      "5-6Y",
      "3-6M",
      "1-2Y"
    ],
    "color": "Rose Gold",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-80/500/650",
    "description": "Baby Boy Dungaree Set crafted from soft, breathable fabric \u2014 a casual favorite designed for comfort and everyday little adventures.",
    "rating": 4.4,
    "reviewCount": 11
  },
  {
    "id": "NC0081",
    "name": "Baby Newborn Gift Set",
    "category": "baby",
    "occasion": "Eid Collection",
    "price": 3890,
    "comparePrice": 0,
    "stock": 10,
    "badge": "",
    "ageGroup": "4-5Y",
    "sizes": [
      "6-12M",
      "0-3M",
      "4-5Y"
    ],
    "color": "Ivory",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-81/500/650",
    "description": "Baby Newborn Gift Set crafted from soft, breathable fabric \u2014 a eid collection favorite designed for comfort and everyday little adventures.",
    "rating": 4.9,
    "reviewCount": 20
  },
  {
    "id": "NC0082",
    "name": "Baby Hooded Romper",
    "category": "baby",
    "occasion": "Wedding Wear",
    "price": 2690,
    "comparePrice": 0,
    "stock": 25,
    "badge": "",
    "ageGroup": "3-4Y",
    "sizes": [
      "6-12M",
      "1-2Y",
      "3-4Y",
      "0-3M",
      "4-5Y"
    ],
    "color": "Powder Blue",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-82/500/650",
    "description": "Baby Hooded Romper crafted from soft, breathable fabric \u2014 a wedding wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.5,
    "reviewCount": 59
  },
  {
    "id": "NC0083",
    "name": "Baby Striped Onesie Set",
    "category": "baby",
    "occasion": "Everyday",
    "price": 2890,
    "comparePrice": 0,
    "stock": 12,
    "badge": "new",
    "ageGroup": "1-2Y",
    "sizes": [
      "3-4Y",
      "2-3Y",
      "5-6Y",
      "6-12M",
      "0-3M"
    ],
    "color": "Mint Green",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-83/500/650",
    "description": "Baby Striped Onesie Set crafted from soft, breathable fabric \u2014 a everyday favorite designed for comfort and everyday little adventures.",
    "rating": 5.0,
    "reviewCount": 108
  },
  {
    "id": "NC0084",
    "name": "Baby Cotton Romper \u2013 Style 2",
    "category": "baby",
    "occasion": "Casual",
    "price": 2890,
    "comparePrice": 2890,
    "stock": 0,
    "badge": "new",
    "ageGroup": "5-6Y",
    "sizes": [
      "1-2Y",
      "3-6M",
      "2-3Y",
      "4-5Y"
    ],
    "color": "Mint Green",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-84/500/650",
    "description": "Baby Cotton Romper \u2013 Style 2 crafted from soft, breathable fabric \u2014 a casual favorite designed for comfort and everyday little adventures.",
    "rating": 4.9,
    "reviewCount": 32
  },
  {
    "id": "NC0085",
    "name": "Baby Floral Onesie \u2013 Style 2",
    "category": "baby",
    "occasion": "Party Wear",
    "price": 2490,
    "comparePrice": 0,
    "stock": 0,
    "badge": "",
    "ageGroup": "3-6M",
    "sizes": [
      "6-12M",
      "2-3Y",
      "5-6Y"
    ],
    "color": "White",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-85/500/650",
    "description": "Baby Floral Onesie \u2013 Style 2 crafted from soft, breathable fabric \u2014 a party wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.3,
    "reviewCount": 48
  },
  {
    "id": "NC0086",
    "name": "Baby Sleep Suit \u2013 Style 2",
    "category": "baby",
    "occasion": "New Arrivals",
    "price": 4690,
    "comparePrice": 0,
    "stock": 12,
    "badge": "new",
    "ageGroup": "3-4Y",
    "sizes": [
      "2-3Y",
      "0-3M",
      "3-6M"
    ],
    "color": "Charcoal Grey",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-86/500/650",
    "description": "Baby Sleep Suit \u2013 Style 2 crafted from soft, breathable fabric \u2014 a new arrivals favorite designed for comfort and everyday little adventures.",
    "rating": 4.3,
    "reviewCount": 60
  },
  {
    "id": "NC0087",
    "name": "Baby Knit Cardigan Set \u2013 Style 2",
    "category": "baby",
    "occasion": "Everyday",
    "price": 4690,
    "comparePrice": 0,
    "stock": 3,
    "badge": "",
    "ageGroup": "0-3M",
    "sizes": [
      "1-2Y",
      "2-3Y",
      "0-3M",
      "4-5Y",
      "6-12M"
    ],
    "color": "Blush Pink",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-87/500/650",
    "description": "Baby Knit Cardigan Set \u2013 Style 2 crafted from soft, breathable fabric \u2014 a everyday favorite designed for comfort and everyday little adventures.",
    "rating": 4.9,
    "reviewCount": 57
  },
  {
    "id": "NC0088",
    "name": "Baby Header Bib Set \u2013 Style 2",
    "category": "baby",
    "occasion": "Casual",
    "price": 3890,
    "comparePrice": 4590,
    "stock": 20,
    "badge": "new",
    "ageGroup": "6-9M",
    "sizes": [
      "3-4Y",
      "2-3Y",
      "3-6M"
    ],
    "color": "Powder Blue",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-88/500/650",
    "description": "Baby Header Bib Set \u2013 Style 2 crafted from soft, breathable fabric \u2014 a casual favorite designed for comfort and everyday little adventures.",
    "rating": 4.7,
    "reviewCount": 94
  },
  {
    "id": "NC0089",
    "name": "Baby Soft Booties Set \u2013 Style 2",
    "category": "baby",
    "occasion": "New Arrivals",
    "price": 2490,
    "comparePrice": 0,
    "stock": 25,
    "badge": "",
    "ageGroup": "5-6Y",
    "sizes": [
      "4-5Y",
      "0-3M",
      "3-4Y",
      "5-6Y"
    ],
    "color": "Sky Blue",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-89/500/650",
    "description": "Baby Soft Booties Set \u2013 Style 2 crafted from soft, breathable fabric \u2014 a new arrivals favorite designed for comfort and everyday little adventures.",
    "rating": 4.5,
    "reviewCount": 116
  },
  {
    "id": "NC0090",
    "name": "Baby Cotton Jumpsuit \u2013 Style 2",
    "category": "baby",
    "occasion": "New Arrivals",
    "price": 1990,
    "comparePrice": 0,
    "stock": 20,
    "badge": "",
    "ageGroup": "1-2Y",
    "sizes": [
      "3-6M",
      "6-12M",
      "1-2Y",
      "4-5Y"
    ],
    "color": "Rose Gold",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-90/500/650",
    "description": "Baby Cotton Jumpsuit \u2013 Style 2 crafted from soft, breathable fabric \u2014 a new arrivals favorite designed for comfort and everyday little adventures.",
    "rating": 4.7,
    "reviewCount": 63
  },
  {
    "id": "NC0091",
    "name": "Baby Party Romper \u2013 Style 2",
    "category": "baby",
    "occasion": "Wedding Wear",
    "price": 1690,
    "comparePrice": 1690,
    "stock": 3,
    "badge": "",
    "ageGroup": "0-3M",
    "sizes": [
      "3-4Y",
      "4-5Y",
      "3-6M"
    ],
    "color": "Burgundy",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-91/500/650",
    "description": "Baby Party Romper \u2013 Style 2 crafted from soft, breathable fabric \u2014 a wedding wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.6,
    "reviewCount": 88
  },
  {
    "id": "NC0092",
    "name": "Baby Fleece Set \u2013 Style 2",
    "category": "baby",
    "occasion": "Wedding Wear",
    "price": 1690,
    "comparePrice": 0,
    "stock": 15,
    "badge": "new",
    "ageGroup": "9-12M",
    "sizes": [
      "2-3Y",
      "6-12M",
      "0-3M",
      "5-6Y"
    ],
    "color": "Lavender",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-92/500/650",
    "description": "Baby Fleece Set \u2013 Style 2 crafted from soft, breathable fabric \u2014 a wedding wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.4,
    "reviewCount": 16
  },
  {
    "id": "NC0093",
    "name": "Baby Muslin Set \u2013 Style 2",
    "category": "baby",
    "occasion": "Wedding Wear",
    "price": 2490,
    "comparePrice": 0,
    "stock": 12,
    "badge": "new",
    "ageGroup": "5-6Y",
    "sizes": [
      "1-2Y",
      "4-5Y",
      "5-6Y",
      "2-3Y"
    ],
    "color": "Blush Pink",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-93/500/650",
    "description": "Baby Muslin Set \u2013 Style 2 crafted from soft, breathable fabric \u2014 a wedding wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.7,
    "reviewCount": 91
  },
  {
    "id": "NC0094",
    "name": "Baby Girl Headband Dress \u2013 Style 2",
    "category": "baby",
    "occasion": "New Arrivals",
    "price": 2190,
    "comparePrice": 2190,
    "stock": 10,
    "badge": "",
    "ageGroup": "3-4Y",
    "sizes": [
      "0-3M",
      "3-6M",
      "4-5Y",
      "2-3Y"
    ],
    "color": "Ivory",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-94/500/650",
    "description": "Baby Girl Headband Dress \u2013 Style 2 crafted from soft, breathable fabric \u2014 a new arrivals favorite designed for comfort and everyday little adventures.",
    "rating": 4.7,
    "reviewCount": 6
  },
  {
    "id": "NC0095",
    "name": "Baby Boy Dungaree Set \u2013 Style 2",
    "category": "baby",
    "occasion": "Eid Collection",
    "price": 1690,
    "comparePrice": 0,
    "stock": 8,
    "badge": "",
    "ageGroup": "2-3Y",
    "sizes": [
      "5-6Y",
      "6-12M",
      "3-6M",
      "4-5Y"
    ],
    "color": "Coral",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-95/500/650",
    "description": "Baby Boy Dungaree Set \u2013 Style 2 crafted from soft, breathable fabric \u2014 a eid collection favorite designed for comfort and everyday little adventures.",
    "rating": 4.7,
    "reviewCount": 116
  },
  {
    "id": "NC0096",
    "name": "Baby Newborn Gift Set \u2013 Style 2",
    "category": "baby",
    "occasion": "Wedding Wear",
    "price": 1490,
    "comparePrice": 2390,
    "stock": 0,
    "badge": "new",
    "ageGroup": "4-5Y",
    "sizes": [
      "5-6Y",
      "3-4Y",
      "1-2Y",
      "4-5Y"
    ],
    "color": "Peach",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-96/500/650",
    "description": "Baby Newborn Gift Set \u2013 Style 2 crafted from soft, breathable fabric \u2014 a wedding wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.8,
    "reviewCount": 17
  },
  {
    "id": "NC0097",
    "name": "Baby Hooded Romper \u2013 Style 2",
    "category": "baby",
    "occasion": "Casual",
    "price": 2490,
    "comparePrice": 0,
    "stock": 10,
    "badge": "",
    "ageGroup": "9-12M",
    "sizes": [
      "2-3Y",
      "0-3M",
      "3-6M",
      "1-2Y",
      "4-5Y"
    ],
    "color": "Powder Blue",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-97/500/650",
    "description": "Baby Hooded Romper \u2013 Style 2 crafted from soft, breathable fabric \u2014 a casual favorite designed for comfort and everyday little adventures.",
    "rating": 4.8,
    "reviewCount": 100
  },
  {
    "id": "NC0098",
    "name": "Baby Striped Onesie Set \u2013 Style 2",
    "category": "baby",
    "occasion": "Wedding Wear",
    "price": 2190,
    "comparePrice": 2190,
    "stock": 0,
    "badge": "",
    "ageGroup": "5-6Y",
    "sizes": [
      "4-5Y",
      "3-6M",
      "5-6Y",
      "1-2Y",
      "3-4Y"
    ],
    "color": "Sage Green",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-98/500/650",
    "description": "Baby Striped Onesie Set \u2013 Style 2 crafted from soft, breathable fabric \u2014 a wedding wear favorite designed for comfort and everyday little adventures.",
    "rating": 4.5,
    "reviewCount": 53
  },
  {
    "id": "NC0099",
    "name": "Baby Cotton Romper \u2013 Style 3",
    "category": "baby",
    "occasion": "Everyday",
    "price": 5190,
    "comparePrice": 0,
    "stock": 15,
    "badge": "new",
    "ageGroup": "3-4Y",
    "sizes": [
      "3-6M",
      "4-5Y",
      "6-12M",
      "2-3Y"
    ],
    "color": "Sky Blue",
    "customSize": false,
    "image": "https://picsum.photos/seed/najiha-99/500/650",
    "description": "Baby Cotton Romper \u2013 Style 3 crafted from soft, breathable fabric \u2014 a everyday favorite designed for comfort and everyday little adventures.",
    "rating": 4.4,
    "reviewCount": 54
  },
  {
    "id": "NC0100",
    "name": "Baby Floral Onesie \u2013 Style 3",
    "category": "baby",
    "occasion": "Everyday",
    "price": 1490,
    "comparePrice": 0,
    "stock": 5,
    "badge": "",
    "ageGroup": "3-4Y",
    "sizes": [
      "3-4Y",
      "0-3M",
      "1-2Y",
      "4-5Y",
      "3-6M"
    ],
    "color": "Charcoal Grey",
    "customSize": true,
    "image": "https://picsum.photos/seed/najiha-100/500/650",
    "description": "Baby Floral Onesie \u2013 Style 3 crafted from soft, breathable fabric \u2014 a everyday favorite designed for comfort and everyday little adventures.",
    "rating": 4.9,
    "reviewCount": 98
  }
];
